config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  
  resources :matches

  namespace 'admin' do
    resources :matches
    resources :courses
    resources :users, only: [:index, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :first_student, :class_name => 'User', :foreign_key => 'first_student_id'
  belongs_to :second_student, :class_name => 'User', :foreign_key => 'second_student_id'

  def self.removeMatches(day)
    #remove current matches for courseday
    existing_matches = Match.where(day: day)

    if existing_matches.length > 0
      existing_matches.each do |match|
        match.destroy
      end
    end
  end

  def self.couplesForCourseday(day)
    day = day.to_date
    couples = makeCouples()

    couples.each do |student|
      new_match = Match.create(first_student: student[0], second_student: student[1], day: day)
    end
  end

  def self.makeCouples()
    couples = []
    picked_students = []
    # query that returns an array with all students (no admins) as objects
    students = User.all.select { |u| u.is_admin == false }
    # add surrogate user to array if number of students is odd
    students.push(User.find{ |u| u.no_teammate == true}) if students.length.odd?
    # amount of couples per day is total students /2
    couples_per_day = students.length / 2

    couples_per_day.times do
      randomizer_first = rand(students.length)
      first_pick = students[randomizer_first]
      picked_students << students.delete_at(randomizer_first)

      randomizer_second = rand(students.length)
      second_pick = students[randomizer_second]
      picked_students << students.delete_at(randomizer_second)

        couples << [first_pick, second_pick]
      end
    return couples
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :match1st, :class_name => 'Match', :foreign_key => 'first_student_id'
   has_many :match2nd, :class_name => 'Match', :foreign_key => 'second_student_id'

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  before_action do
    check_admin
  end

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to :admin_courses, notice: "Course successfully created"
    else
      render :new
    end
  end

  def destroy
    @course.destroy
    redirect_to :admin_courses, :notice => "Course has been deleted"
  end

  private

  def course_params
    params.require(:course).permit(:name, :amount_of_days, :start_date, :end_date)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def check_admin
    redirect_to "/", alert: 'This page is for Teachers & Staff only.' unless current_user.is_admin
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  before_action :authenticate_user!

  before_action do
    check_admin
  end

  def index
    matches_index = Match.all
    @matches = matches_index.group_by(&:day)
  end

  def create
    Match.removeMatches(params[:day])
    Match.couplesForCourseday(params[:day])
    redirect_to admin_matches_path, notice: "Matches created"
  end

  def delete
    Match.removeMatches(params[:day])
    redirect_to admin_matches, notice: "Matches deleted"
  end

  def check_admin
    redirect_to "/", alert: 'This page is for Teachers & Staff only.' unless current_user.is_admin
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to :admin_users, notice: "Admin status updated"
    else
      redirect_to 'pages#home'
    end
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
      added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def home
  end

  def index
    matches_index = Match.all

    studentmatches = matches_index.select do |match|
      match.first_student_id == current_user.id.to_s || match.second_student_id == current_user.id.to_s
    end

    @studentmatches = studentmatches.select do |match|
      match.day <= Date.today
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/coursedays/index.html.erb
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
     <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Coursedays</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @coursedays.each do |courseday| %>
            <div class="col-md-7">
              <h4>Courseday name</h4>
              <hr>
            </div>
            <div class="col-md-3 right">

            </div>
          <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/admin/courses/_form.html.erb
<%= form_for [:admin, @course] do |f| %>

  <% @course.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger" role="alert"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>Course Name</label>
    <%= f.text_field :name, placeholder: "Name of the course", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Length of course in days</label>
    <div class="input-group">
      <%= f.number_field :amount_of_days, placeholder: "How many days does this course take", class: "form-control" %>
    </div>
  </div>
  <hr>

 <div class="actions">
   <%= f.submit "Save", class: "btn btn-primary" %>
 </div>
<% end %>

app/views/admin/courses/index.html.erb
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
     <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Courses</h3>
          <%= link_to "Make new course", new_admin_course_url, class: "btn btn-default" %>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @courses.each do |course| %>
            <div class="col-md-7">
              <h4><%= course.name %></h4>
              <h4>Length of course in days: <%= course.amount_of_days %></h4>
              <hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Delete", admin_course_path(course), class: "btn btn-default", :method => :delete %>
            </div>
          <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/admin/courses/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Add a new course</h3>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/matches/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Couples</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% (Date.today.beginning_of_week .. Date.today.end_of_week).each do |day| %>
              <div class="col-md-7">
                <h4><%= day.strftime('%d/%m/%Y') %></h4>
                <% @matches[day].to_a.each do |match| %>
                <%= day %> | <%= match.first_student.name %> & <%= match.second_student.name %> <br>
                <%end%>
              </div>
              <div class="col-md-3">
                <%= link_to "Create matches", admin_matches_path(day: day), class: "btn btn-default", method: :create %>
              </div>
            <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
     <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Users</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @users.each do |user| %>
            <div class="col-md-7">
              <!-- <%= debug user %> -->
              <h4><%= user.name %></h4>
              <p><%= user.email %></p>
              <h4><% if user.is_admin? %> ADMIN <%end%></h4>
              <hr>
            </div>
            <div class="col-md-3 right">
                <%= form_for [:admin, user], method: :put do |f| %>
                <%= hidden_field_tag :is_admin, '' %>
                <%= f.check_box :is_admin %>
                <%= f.submit "Update" %>
              <% end %>
              <!-- <p>Admin yes/no</p> <%= check_box_tag :is_admin, 1, user.is_admin? ? true : false, { class: 'user', data: { id: user.id} } %> -->
            </div>
          <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Findyourmatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/matches/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Your Matches</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @studentmatches.each do |match|  %>
              <div class="col-md-10">
                <h4><%= match.day %> | <%= match.first_student.name %> & <%= match.second_student.name %></h4>
                <hr>
              </div>
              <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Co-opdaisseur</title>

    <link href="../../assets/stylesheets/jumbotron.scss" rel="stylesheet">

  </head>

  <body>
    <div class="jumbotron">
      <div class="container">
        <% if !user_signed_in? %>
        <h1>Welcome to Co-opdaisseur! </h1>
        <p>Find out who you are paired up with today, and see who you worked with before, by logging in!</p>
        <p><%= link_to "Log In", new_user_session_path, class: "btn btn-primary btn-lg" %></p>
        <% else %>
        <h1>Welcome to co-opdaisseur! </h1>
          <% if current_user.is_admin? %>
            <p>Welcome <%= current_user.name %>
            <p><%= link_to "View and Create Matches", admin_matches_path, class: "btn btn-success btn-lg" %></p>
            <p><%= link_to "View and Create Courses", admin_courses_path, class: "btn btn-success btn-lg" %></p>
            <p><%= link_to "  View and Edit Users  ", admin_users_path, class: "btn btn-success btn-lg" %></p>
          <% else %>
            <h3><%= current_user.name %> </h3>
            <p>click the link below to see your matches.
            <p><%= link_to "Matches", matches_path, class: "btn btn-primary btn-lg" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Co-opdaisseur", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
        <% end %>
      </ul>
    </div>
  </div>
</nav>